CREATE TABLE IF NOT EXISTS agent_contexts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  content TEXT NOT NULL DEFAULT '',
  created_by UUID REFERENCES users(id),
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

ALTER TABLE groups ADD COLUMN IF NOT EXISTS context TEXT NOT NULL DEFAULT '';

ALTER TABLE flows ADD COLUMN IF NOT EXISTS flow_context TEXT NOT NULL DEFAULT '';
