apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "core-agents.fullname" . }}-scheduler
  labels:
    {{- include "core-agents.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.scheduler.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "core-agents.fullname" . }}-scheduler
  template:
    metadata:
      labels:
        app: {{ include "core-agents.fullname" . }}-scheduler
    spec:
      containers:
        - name: scheduler
          image: "{{ .Values.image.repository }}-scheduler:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: VALKEY_HOST
              value: {{ include "core-agents.fullname" . }}-valkey
          envFrom:
            - secretRef:
                name: {{ include "core-agents.fullname" . }}-secret
          resources:
            {{- toYaml .Values.scheduler.resources | nindent 12 }}
